server:
  port: 8871

spring:
  application:
    name: product-service

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

env: dev
branch: master